title: "M.P."
#mailto: mirco.paccusse@gmail.com 
github_username: pax80
email: mirco.paccusse@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  🚀 curious / nvim / otel / software engineering
#baseurl: "" # the subpath of your site, e.g. /blog

url: "https://pax80.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#github_username:  pax80
#
# Build settings
theme: minima
minima:
  skin: solarized-light
plugins:
  - jekyll-feed
  #  - jekyll-sitemap
