plugins:
  - jekyll-feed
  - jekyll-sitemap
  #  - jekyll-remote-theme


email: mirco.paccusse@gmail.com
description: >-
  🚀 curious / nvim / otel / software engineering
baseurl: /
url: "https://pax80.github.io" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics: G-9WQLX34DJH

show_excerpts: true
excerpt_separator: <!--more-->
theme: minima
minima:
  skin: solarized-light
title: "M.P." 
header_pages:
  - tags.md
  - blog.md
  - about.md

minima:
  social_links:
    - { platform: linkedin, user_url: "https://linkedin.com/in/hatedabamboo/"}
    - { platform: github,  user_url: "https://github.com/pax80/" }
    - { platform: twitter, user_url: "https://twitter.com/paccusse80/" }
